commands:
  actionbar: true
  title: true

messages:
  reloaded: '<color:#77DD77>âœ” Ê€á´‡ÊŸá´á´€á´…á´‡á´…. The configuration has been reloaded.'
  command_disabled: "<color:#FAA0A0>âœ– á´‡Ê€Ê€á´Ê€. This command is disabled in the config."

global_disabled_servers:
  - servername12345

autotitles_enabled: false
autotitles:
  anyname1:
      title: "<color:#FFD700>ğŸŒŸ á´›Éªá´›ÊŸá´‡"
      subtitle: "<color:#FFD700>ğŸŒŸ sá´œÊ™á´›Éªá´›ÊŸá´‡" # optional
      time: 30s
      fade: 1 # optional
      stay: 1 # optional
      fadeout: 1 # optional
      disabled_servers: # optional
        - servername12345
  # anyname2:
  #   title: "<color:#FFD700>ğŸŒŸ á´›Éªá´›ÊŸá´‡"
  #   subtitle: "<color:#FFD700>ğŸŒŸ sá´œÊ™á´›Éªá´›ÊŸá´‡"
  #   time: 30s